# Generated by Django 6.0.3 on 2026-05-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('target_count', models.PositiveIntegerField(choices=[(30, '30個'), (50, '50個'), (70, '70個'), (100, '100個')], default=100)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='IdeaMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='思いつきメモ')),
                ('note', models.TextField(blank=True, verbose_name='補足')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='対象月')),
                ('title', models.CharField(max_length=200, verbose_name='月の目標')),
                ('is_done', models.BooleanField(default=False, verbose_name='達成済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='やりたいこと')),
                ('description', models.TextField(blank=True, verbose_name='メモ')),
                ('is_done', models.BooleanField(default=False, verbose_name='達成済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='週の開始日')),
                ('title', models.CharField(max_length=200, verbose_name='週の目標')),
                ('is_done', models.BooleanField(default=False, verbose_name='達成済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_goals', to='goals.monthlygoal', verbose_name='紐づく月目標')),
            ],
            options={
                'ordering': ['-week_start', 'is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(max_length=200, verbose_name='今日やること')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='today_tasks', to='goals.weeklygoal', verbose_name='紐づく週目標')),
            ],
            options={
                'ordering': ['date', 'is_done', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='yearly_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_goals', to='goals.yearlygoal', verbose_name='紐づく年間目標'),
        ),
    ]
