# Generated by Django 6.0.3 on 2026-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='予定日'),
        ),
    ]
