# Generated by Django 6.0.3 on 2026-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_yearlygoal_planned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
    ]
