# Generated by Django 6.0.3 on 2026-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_yearlygoal_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
