# Generated by Django 6.0.3 on 2026-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_yearlygoal_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='category',
            field=models.CharField(choices=[('travel', '旅行'), ('beauty', '美容'), ('study', '勉強'), ('work', '仕事'), ('hobby', '趣味'), ('health', '健康'), ('money', 'お金'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
