# Generated by Django 6.0.3 on 2026-05-04 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_and_assign_existing_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("goals", "Profile")
    YearlyGoal = apps.get_model("goals", "YearlyGoal")
    IdeaMemo = apps.get_model("goals", "IdeaMemo")

    for user in User.objects.all():
        Profile.objects.get_or_create(
            user=user,
            defaults={"display_name": user.username},
        )

    owner = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if owner:
        YearlyGoal.objects.filter(user__isnull=True).update(user=owner)
        IdeaMemo.objects.filter(user__isnull=True).update(user=owner)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_yearlygoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideamemo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_memos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80, verbose_name='表示名')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_and_assign_existing_data, noop_reverse),
    ]
