# Generated by Django 6.0.3 on 2026-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_ideamemo_user_yearlygoal_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='item_is_public',
            field=models.BooleanField(default=True, verbose_name='この項目を公開する'),
        ),
    ]
