# Generated by Django 6.0.3 on 2026-05-07 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_year_plans(apps, schema_editor):
    User = apps.get_model("auth", "User")
    GoalSetting = apps.get_model("goals", "GoalSetting")
    YearlyGoal = apps.get_model("goals", "YearlyGoal")
    YearPlan = apps.get_model("goals", "YearPlan")

    current_year = 2026
    default_setting = GoalSetting.objects.filter(year=current_year).first()
    target_count = default_setting.target_count if default_setting else 100

    for user in User.objects.all():
        is_public = YearlyGoal.objects.filter(user=user, is_public=True).exists()
        YearPlan.objects.get_or_create(
            user=user,
            year=current_year,
            defaults={
                "target_count": target_count,
                "is_public": is_public,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_yearlygoal_item_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('target_count', models.PositiveIntegerField(choices=[(30, '30個'), (50, '50個'), (70, '70個'), (100, '100個')], default=100, verbose_name='Target count')),
                ('is_public', models.BooleanField(default=False, verbose_name='この年のリストを公開する')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_plans', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='unique_year_plan_per_user')],
            },
        ),
        migrations.RunPython(create_year_plans, noop_reverse),
    ]
