# Generated by Django 6.0.3 on 2026-05-11 13:03

from django.db import migrations, models


def fill_list_titles(apps, schema_editor):
    YearPlan = apps.get_model("goals", "YearPlan")
    for plan in YearPlan.objects.filter(list_title=""):
        plan.list_title = f"{plan.year}年やりたいこと"
        plan.save(update_fields=["list_title"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0008_yearplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearplan",
            name="list_title",
            field=models.CharField(blank=True, max_length=120, verbose_name="リスト名"),
        ),
        migrations.RunPython(fill_list_titles, noop_reverse),
    ]
