# Generated by Django 6.0.3 on 2026-05-11 13:22

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def attach_existing_goals_to_default_plan(apps, schema_editor):
    YearPlan = apps.get_model("goals", "YearPlan")
    YearlyGoal = apps.get_model("goals", "YearlyGoal")
    current_year = timezone.now().year

    user_ids = (
        YearlyGoal.objects.filter(year_plan__isnull=True, user__isnull=False)
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids:
        plan = YearPlan.objects.filter(user_id=user_id, year=current_year).order_by("pk").first()
        if plan is None:
            plan = YearPlan.objects.create(
                user_id=user_id,
                year=current_year,
                list_title=f"{current_year}年やりたいこと",
                target_count=100,
                is_public=False,
            )
        YearlyGoal.objects.filter(
            user_id=user_id,
            year_plan__isnull=True,
        ).update(year_plan=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_yearplan_list_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='yearplan',
            name='unique_year_plan_per_user',
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='year_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.yearplan', verbose_name='マイリスト'),
        ),
        migrations.RunPython(attach_existing_goals_to_default_plan, migrations.RunPython.noop),
    ]
