# Generated by Django 6.0.3 on 2026-05-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_yearplan_unique_year_plan_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
