# Generated by Django 6.0.3 on 2026-05-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_likelist_savedlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantToTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_by', to='goals.yearlygoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_item'), name='unique_want_to_try_per_user')],
            },
        ),
    ]
