# Generated by Django 6.0.3 on 2026-05-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_todo_dates_and_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    MonthlyGoal = apps.get_model("goals", "MonthlyGoal")
    WeeklyGoal = apps.get_model("goals", "WeeklyGoal")
    TodayTask = apps.get_model("goals", "TodayTask")
    default_user = User.objects.order_by("pk").first()

    for goal in MonthlyGoal.objects.all():
        goal.target_month = goal.month
        if goal.user_id is None and default_user:
            goal.user_id = default_user.pk
        goal.save(update_fields=["target_month", "user"])

    for goal in WeeklyGoal.objects.all():
        goal.week_start_date = goal.week_start
        if goal.user_id is None and default_user:
            goal.user_id = default_user.pk
        goal.save(update_fields=["week_start_date", "user"])

    for task in TodayTask.objects.all():
        task.scheduled_date = task.date
        if task.user_id is None and default_user:
            task.user_id = default_user.pk
        task.save(update_fields=["scheduled_date", "user"])


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlygoal',
            options={'ordering': ['-target_month', 'is_done', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='todaytask',
            options={'ordering': ['scheduled_date', 'is_done', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='weeklygoal',
            options={'ordering': ['-week_start_date', 'is_done', '-created_at']},
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='target_month',
            field=models.DateField(blank=True, null=True, verbose_name='対象月'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_todos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='todaytask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='予定日'),
        ),
        migrations.AddField(
            model_name='todaytask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_todos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_todos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='week_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='週の開始日'),
        ),
        migrations.RunPython(backfill_todo_dates_and_user, migrations.RunPython.noop),
    ]
