# Generated by Django 6.0.3 on 2026-05-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_alter_monthlygoal_options_alter_todaytask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons/', verbose_name='プロフィールアイコン'),
        ),
        migrations.CreateModel(
            name='ListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('my_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goals.yearplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TogetherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('accepted', '承認済み'), ('rejected', '拒否')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='together_requests', to='goals.yearlygoal')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_together_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_together_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('requester', 'list_item'), name='unique_together_request_per_item'), models.CheckConstraint(condition=models.Q(('requester', models.F('receiver')), _negated=True), name='prevent_self_together_request')],
            },
        ),
    ]
