# Generated by Django 6.0.3 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_profile_icon_listcomment_togetherrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsetting',
            name='target_count',
            field=models.PositiveIntegerField(choices=[(10, '10個'), (20, '20個'), (30, '30個'), (50, '50個'), (70, '70個'), (100, '100個')], default=100),
        ),
        migrations.AlterField(
            model_name='yearplan',
            name='target_count',
            field=models.PositiveIntegerField(choices=[(10, '10個'), (20, '20個'), (30, '30個'), (50, '50個'), (70, '70個'), (100, '100個')], default=100, verbose_name='Target count'),
        ),
    ]
