# Generated by Django 6.0.3 on 2026-06-24 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0019_profile_is_private_followrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_yearly_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_yearly_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearplan',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_year_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearplan',
            name='is_collaborative',
            field=models.BooleanField(default=False, verbose_name='共同リスト'),
        ),
    ]
