# Generated by Django 6.0.3 on 2026-06-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0021_collaborationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='completed_note',
            field=models.TextField(blank=True, verbose_name='達成後の記録'),
        ),
        migrations.CreateModel(
            name='GoalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goal_images/', verbose_name='画像')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='キャプション')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goals.yearlygoal', verbose_name='やりたいこと')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='リンクタイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='goals.yearlygoal', verbose_name='やりたいこと')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
