# Generated by Django 6.0.3 on 2026-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_yearlygoal_completed_note_goalimage_goallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='yearplan',
            name='icon',
            field=models.CharField(blank=True, default='checklist', max_length=20, verbose_name='アイコン'),
        ),
    ]
