# Generated by Django 6.0.3 on 2026-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0025_yearplan_template_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
    ]
