# Generated by Django 6.0.3 on 2026-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0028_clear_existing_yearplan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='鍵アカウント'),
        ),
    ]
