# Generated by Django 6.0.3 on 2026-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0029_alter_profile_bio_alter_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplan',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='説明'),
        ),
    ]
