# Generated by Django 6.0.3 on 2026-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0030_alter_yearplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplan',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='yearplan',
            name='list_title',
            field=models.CharField(blank=True, max_length=30, verbose_name='リスト名'),
        ),
    ]
