# Generated by Django 6.0.3 on 2026-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0031_alter_yearplan_description_alter_yearplan_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='名前'),
        ),
    ]
