# Generated by Django 6.0.3 on 2026-08-09 03:53

from django.db import migrations, models


def fill_blank_display_names(apps, schema_editor):
    Profile = apps.get_model('goals', 'Profile')
    for profile in Profile.objects.select_related('user').filter(display_name=''):
        profile.display_name = profile.user.username[:15] or f'user{profile.user_id}'
        profile.save(update_fields=['display_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0032_alter_profile_display_name'),
    ]

    operations = [
        migrations.RunPython(fill_blank_display_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=15, verbose_name='表示名'),
        ),
    ]
